---
# This will remove httpd webserver
  
  - name: Stopping httpd service
    service:
      name: httpd
      state: stopped

  - name: ensure httpd is stopped
    service:
      name: httpd
      state: stopped

  - name: Remove apache packages 
    yum:
      name: httpd
      state: absent


